# Desarrollo Web en Entorno Servidor
# Docker

version: '3'

services:
    #
    # WEB
    web:
        build: .
        container_name: relacion-1
        volumes:
            - ./html:/var/www/html
        ports:
            - '80:80'
        links:
            - 'db:db'
    #
    # DATABASE
    db:
        image: mysql:latest
        container_name: dwes-db
        restart: always
        command: --default-authentication-plugin=mysql_native_password

        environment:
            MYSQL_DATABASE: mibasedatos
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

        ports:
         - '3306:3306'

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: dwes-phpmyadmin
        restart: always
        ports:
         - '8080:80'
        environment:
            - PMA_HOST=db
            - MYSQL_USER=root
            - PMA_ARBITRARY=1
        
        